APIの実装
SoichiroInagaki/tasks_management_by_inagaki pull request #2
Opened 2024-07-19 06:04 UTC by SoichiroInagaki

未実装だった、タスクを新規登録するAPI・特定タスクを取得するAPI・編集するAPI・削除するAPIをそれぞれ実装しました。

2024-07-20 02:19 UTC, shota-ootani-excite requested changes
レビューしました。

私のリポジトリも共有しておきます。
https://github.com/shota-ootani-excite/spring-boot-training-api
レビュー指摘対応が終わったら、参考に見てみてください。

2024-07-20 02:19 UTC, shota-ootani-excite commented on src/main/java/com/tq_ojd/tasks_management/app/TaskForm.java
> +package com.tq_ojd.tasks_management.app;
application層だけパッケージ階層が異なります。
下にcontrollerやresourceパッケージを作ると、domainやinfraと同じ階層になると思います。

2024-07-20 02:19 UTC, shota-ootani-excite commented on src/main/java/com/tq_ojd/tasks_management/app/TaskForm.java
> +  private String title;
IDがないと、画面と繋げるときに困るかと思います。
RequestBodyとResponseBodyは別クラスにしておくと良いです。

2024-07-20 02:19 UTC, shota-ootani-excite commented on src/main/java/com/tq_ojd/tasks_management/app/TaskManagementController.java
>    TasksManagementService tasksManagementService;
privateアクセス修飾子をつけてください。

2024-07-20 02:19 UTC, shota-ootani-excite commented on src/main/java/com/tq_ojd/tasks_management/app/TaskManagementController.java
> +  public ResponseEntity<?> delete(@PathVariable int id){
`ResponseEntity<Void>` で良いと思います。

2024-07-20 02:19 UTC, shota-ootani-excite commented on src/main/java/com/tq_ojd/tasks_management/app/TaskManagementController.java
> +    return ResponseEntity.noContent().build();
この書き方でHTTPステータス200が返却されますか？
（他と書き方が異なるので確認の意図です。）

2024-07-20 02:19 UTC, shota-ootani-excite commented on src/main/java/com/tq_ojd/tasks_management/domain/service/TasksManagementService.java
> +    getTask(id);
`getTask(id);` は不要かと思います。

2024-07-22 02:28 UTC, SoichiroInagaki commented
レビューを参考に、修正を行いました。

IDフィールドを持つクラスに関しては、新しくTaskOutputクラスを作成した上で値を詰め替え、return部のResponseEntity.ok()メソッドの引数に渡しています。
privateの修飾子に関しては、今まで修飾子を付与していなかったServiceクラスとのAutowired部分に付与しました。
noContent()メソッドについては、参考にしていたページで使用されていたもので、ステータス200ではなく、リクエストは成功したがコンテンツはないことを表すステータス204が返されるそうです。ok().build()に変更し、ステータス200を返すように変更しました。

以上、ご確認よろしくお願いします。

2024-07-22 06:55 UTC, shota-ootani-excite approved these changes
Approveしました。
今回は良いですが、今後は各レビュー指摘に対してはどのように対応したか、個別にコメントをお願いします。

2024-07-22 07:31 UTC, merged